# Configuration settings for PatternScout

# Data Sources
data_sources:
  csv:
    enabled: true
    directory: "data/csv/"
  mongodb:
    enabled: false
    host: "localhost"
    port: 27017
    database: "market_data"
    collection: "ohlcv"

# Pattern Recognition Parameters
pattern_detection:
  flagpole:
    min_bars: 4                # 最少4个15分钟K线（1小时）
    max_bars: 20               # 最多20个15分钟K线（5小时）
    min_height_percent: 1.5    # 最小涨跌幅1.5%
    max_height_percent: 10.0   # 最大涨跌幅10%
    volume_surge_ratio: 2.0    # 成交量激增倍数
    max_retracement: 0.3       # 最大回撤30%
    min_trend_strength: 0.7    # 最小趋势强度（R²）
    
  flag:
    min_bars: 8                # 最少8个15分钟K线（2小时）
    max_bars: 48               # 最多48个15分钟K线（12小时）
    min_slope_angle: 0.5       # 最小倾斜角度0.5度（适应15分钟数据）
    max_slope_angle: 10        # 最大倾斜角度10度（适应15分钟数据）
    retracement_range: [0.2, 0.6]  # 回撤范围20%-60%
    volume_decay_threshold: 0.7     # 成交量衰减阈值
    parallel_tolerance: 0.15        # 平行度容忍度
    min_touches: 2                  # 最少触及边界次数
    
  pennant:
    min_duration_days: 2       # Minimum pennant formation duration
    max_duration_days: 15      # Maximum pennant formation duration (增加从10)
    convergence_ratio: 0.6     # Required convergence ratio (降低从0.7)
    min_convergence_angle: 5   # Minimum convergence angle in degrees
    max_convergence_angle: 45  # Maximum convergence angle in degrees
    
  volume:
    flagpole_volume_threshold: 1.0    # Flagpole volume threshold (降低从1.2)
    flag_volume_decrease: 0.9         # Flag volume decrease ratio (增加从0.8)
    pennant_volume_decrease: 0.8      # Pennant volume decrease ratio
    
  scoring:
    min_confidence_score: 0.5         # Minimum confidence score for pattern acceptance

# Technical Indicators
indicators:
  moving_averages: [5, 10, 20, 50]
  rsi_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_period: 20
  bollinger_std: 2

# Scoring System
scoring:
  pattern_completeness: 0.30
  technical_confirmation: 0.25
  volume_confirmation: 0.25
  historical_success_rate: 0.20

# Output Settings
output:
  base_path: "output"
  data_path: "output/data"
  charts_path: "output/charts"
  reports_path: "output/reports"
  charts:
    format: "png"
    width: 1200
    height: 800
    dpi: 300
  dataset:
    format: "json"
    backup_enabled: true

# Logging
logging:
  level: "INFO"
  file: "logs/pattern_scout.log"
  max_size: "10MB"
  backup_count: 5