# Configuration for Dynamic Baseline Flag Pattern Recognition System
# 动态基线旗形识别系统配置文件

# Data Sources
data_sources:
  csv:
    enabled: true
    directory: "data/csv/"
  mongodb:
    enabled: false
    host: "localhost"
    port: 27017
    database: "market_data"
    collection: "ohlcv"

# Dynamic Baseline System Configuration (Stage 0)
dynamic_baseline:
  history_window: 500              # 滚动统计样本大小
  min_stable_samples: 50           # 最少稳定样本数
  cold_start_threshold: 200        # 冷启动阈值
  
  # Robust Statistics Configuration
  robust_statistics:
    winsorize_limits: [0.02, 0.98] # 缩尾处理百分位数范围
    mad_threshold: 2.5             # MAD异常值检测阈值
    stability_threshold: 0.7       # 稳定性阈值
    
  # Market Regime Detection
  regime_detection:
    atr_period: 100                # ATR计算周期
    high_volatility_threshold: 0.65 # 高波动阈值（百分位数）
    low_volatility_threshold: 0.35  # 低波动阈值（百分位数）
    stability_buffer: 5             # 状态切换确认次数
    
  # Dynamic Thresholds for Different Regimes
  regime_thresholds:
    high_volatility:
      slope_score:
        p75: 1.0
        p85: 1.5
        p90: 2.2
        p95: 3.0
      volume_burst:
        p75: 2.0
        p85: 2.8
        p90: 3.5
        p95: 4.5
      retrace_depth:
        p50: 0.25
        p60: 0.30
        p75: 0.40
        p85: 0.50
      volume_contraction:
        p40: 0.85
        p50: 0.75
        p60: 0.65
        p75: 0.55
      volatility_drop:
        p50: 0.85
        p75: 0.75
        p85: 0.65
      channel_width:
        p20: 0.15
        p50: 0.30
        p80: 0.60
        
    low_volatility:
      slope_score:
        p75: 0.8
        p85: 1.2
        p90: 1.8
        p95: 2.5
      volume_burst:
        p75: 1.8
        p85: 2.3
        p90: 2.8
        p95: 3.5
      retrace_depth:
        p50: 0.20
        p60: 0.25
        p75: 0.35
        p85: 0.45
      volume_contraction:
        p40: 0.80
        p50: 0.70
        p60: 0.60
        p75: 0.50
      volatility_drop:
        p50: 0.80
        p75: 0.70
        p85: 0.60
      channel_width:
        p20: 0.10
        p50: 0.25
        p80: 0.50

# Pattern Detection Configuration (Unified)
pattern_detection:
  flag_pattern:
    # Flagpole Configuration (Stage 1)
    flagpole:
      # Dynamic K-line Range by Timeframe
      bars_range:
        "1m": {min: 8, max: 25}
        "5m": {min: 6, max: 20}
        "15m": {min: 4, max: 15}
        "1h": {min: 3, max: 12}
        "4h": {min: 2, max: 8}
        "1d": {min: 2, max: 6}
      
      # Fixed Validation Thresholds
      fixed_thresholds:
        impulse_bar_ratio: 0.70        # 高动量K线占比阈值
        max_retracement: 0.20          # 最大内部回撤比例
        min_trend_strength: 0.3        # 最小趋势强度（R²）
        
      # Gap Detection Configuration
      gap_detection:
        min_gap_percent: 0.02          # 最小缺口百分比
        max_gap_percent: 0.10          # 最大缺口百分比
        confirmation_bars: 2           # 缺口后确认K线数

    # Flag Detection Configuration (Stage 2)  
    flag:
      # Timeout Rules (adaptive based on regime)
      timeout_multipliers:
        high_volatility: 3             # 高波动时的超时倍数
        low_volatility: 7              # 低波动时的超时倍数
        default: 5                     # 默认超时倍数
        
      # Flag Bars Range by Timeframe
      flag_bars_range:
        "1m": {min: 15, max: 60}
        "5m": {min: 12, max: 48}
        "15m": {min: 8, max: 40}
        "1h": {min: 6, max: 30}
        "4h": {min: 4, max: 20}
        "1d": {min: 3, max: 15}
        
      # Consolidation Filter Thresholds (will use dynamic baselines)
      consolidation_filter:
        enable_dynamic_thresholds: true
        
      # Geometric Pattern Analysis
      geometric_analysis:
        percentile_channel:
          upper_percentile: 0.95       # 上通道分位数
          lower_percentile: 0.05       # 下通道分位数
          min_window: 3                # 最小滚动窗口
          
        pattern_classification:
          parallel_threshold: 0.001     # 平行度阈值（归一化斜率差）
          convergence_threshold: 0.4   # 收敛度阈值
          
      # Pattern Stability Validation
      stability_validation:
        min_containment_ratio: 0.80    # 最小包含比例
        min_touch_count: 2             # 最小触及次数
        min_r_squared: 0.3             # 最小拟合度
        
      # Invalidation Signal Detection
      invalidation_detection:
        fake_breakout:
          volume_multiplier: 1.2       # 假突破成交量倍数阈值
          return_confirmation: 1       # 回归确认K线数
          
        volatility_decay:
          enable_monitoring: true      # 启用波动衰减监控
          min_decay_slope: -0.001     # 最小衰减斜率
          
        volume_divergence:
          max_increase_rate: 0.10     # 最大成交量增长率

    # Pennant Configuration (similar structure)
    pennant:
      timeout_multipliers:
        high_volatility: 3
        low_volatility: 7
        default: 5
      flag_bars_range:
        "1m": {min: 15, max: 60}
        "5m": {min: 12, max: 48}
        "15m": {min: 8, max: 40}
        "1h": {min: 6, max: 30}
        "4h": {min: 4, max: 20}
        "1d": {min: 3, max: 15}
      geometric_analysis:
        percentile_channel:
          upper_percentile: 0.95
          lower_percentile: 0.05
          min_window: 3
        pattern_classification:
          parallel_threshold: 0.001
          convergence_threshold: 0.4

# Legacy Configuration (for backward compatibility)
flagpole_detection:
  # Dynamic K-line Range by Timeframe
  bars_range:
    "1m": {min: 8, max: 25}
    "5m": {min: 6, max: 20}
    "15m": {min: 4, max: 15}
    "1h": {min: 3, max: 12}
    "4h": {min: 2, max: 8}
    "1d": {min: 2, max: 6}
  
  # Fixed Validation Thresholds
  fixed_thresholds:
    impulse_bar_ratio: 0.70        # 高动量K线占比阈值
    max_retracement: 0.20          # 最大内部回撤比例
    min_trend_strength: 0.3        # 最小趋势强度（R²）
    
  # Gap Detection Configuration
  gap_detection:
    min_gap_percent: 0.02          # 最小缺口百分比
    max_gap_percent: 0.10          # 最大缺口百分比
    confirmation_bars: 2           # 缺口后确认K线数

# Dynamic Flag Detection (Stage 2)
flag_detection:
  # Timeout Rules (adaptive based on regime)
  timeout_multipliers:
    high_volatility: 3             # 高波动时的超时倍数
    low_volatility: 7              # 低波动时的超时倍数
    default: 5                     # 默认超时倍数
    
  # Flag Bars Range by Timeframe
  flag_bars_range:
    "1m": {min: 15, max: 60}
    "5m": {min: 12, max: 48}
    "15m": {min: 8, max: 40}
    "1h": {min: 6, max: 30}
    "4h": {min: 4, max: 20}
    "1d": {min: 3, max: 15}
    
  # Consolidation Filter Thresholds (will use dynamic baselines)
  consolidation_filter:
    enable_dynamic_thresholds: true
    
  # Geometric Pattern Analysis
  geometric_analysis:
    percentile_channel:
      upper_percentile: 0.95       # 上通道分位数
      lower_percentile: 0.05       # 下通道分位数
      min_window: 3                # 最小滚动窗口
      
    pattern_classification:
      parallel_threshold: 0.001     # 平行度阈值（归一化斜率差）
      convergence_threshold: 0.4   # 收敛度阈值
      
  # Pattern Stability Validation
  stability_validation:
    min_containment_ratio: 0.80    # 最小包含比例
    min_touch_count: 2             # 最小触及次数
    min_r_squared: 0.3             # 最小拟合度
    
  # Invalidation Signal Detection
  invalidation_detection:
    fake_breakout:
      volume_multiplier: 1.2       # 假突破成交量倍数阈值
      return_confirmation: 1       # 回归确认K线数
      
    volatility_decay:
      enable_monitoring: true      # 启用波动衰减监控
      min_decay_slope: -0.001     # 最小衰减斜率
      
    volume_divergence:
      max_increase_rate: 0.10     # 最大成交量增长率

# Pattern Outcome Tracking (Stage 3)
outcome_tracking:
  # Monitoring Configuration
  monitoring:
    enable_auto_start: true        # 自动开始监控新检测的形态
    max_concurrent: 100            # 最大并发监控数量
    
  # Timeout Configuration
  timeout_rules:
    base_multiplier: 8             # 基础超时倍数（相对形态持续时间）
    max_timeout_hours: 168         # 最大超时时间（7天）
    
  # Outcome Classification Thresholds
  classification_thresholds:
    target_achievement: 1.0        # 目标达成比例
    standard_continuation: 1.5     # 标准延续风险距离倍数
    risk_distance_base: 1.0        # 基础风险距离
    stagnation_range: 0.5          # 停滞区间（相对风险距离）
    
  # Analysis Configuration
  analysis:
    enable_statistical_analysis: true
    export_detailed_results: true
    generate_performance_reports: true

# Technical Indicators
technical_indicators:
  atr_period: 14
  volume_ma_period: 20
  volatility_window: 20
  trend_strength_window: 10

# Output Configuration
output:
  base_path: "output"
  data_path: "output/data"
  charts_path: "output/charts"
  reports_path: "output/reports"
  
  # Chart Generation
  charts:
    format: "png"
    width: 1400
    height: 900
    dpi: 300
    enable_outcome_charts: true    # 生成结局分析图表
    
  # Data Export
  data_export:
    format: "json"
    backup_enabled: true
    export_baselines: true         # 导出基线数据
    export_outcomes: true          # 导出结局数据
    
  # Database Configuration
  database:
    enable_sqlite: true
    db_path: "output/data/patterns.db"
    enable_baseline_storage: true  # 存储基线数据
    enable_outcome_storage: true   # 存储结局数据

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/pattern_scout.log"
  max_size: "20MB"
  backup_count: 10
  
  # Component-specific logging levels
  component_levels:
    dynamic_baseline: "DEBUG"
    regime_detector: "INFO"
    flagpole_detector: "INFO"
    flag_detector: "INFO"
    outcome_tracker: "INFO"

# Performance Configuration
performance:
  enable_caching: true
  cache_size_limit: 1000           # 缓存条目数限制
  enable_parallel_processing: false # 并行处理（实验性）
  max_workers: 4                   # 最大工作线程数

# Advanced Features
advanced_features:
  enable_machine_learning: false   # 机器学习增强（预留）
  enable_real_time_monitoring: false # 实时监控（预留）
  enable_alert_system: false       # 告警系统（预留）
  
# Validation and Quality Control
validation:
  enable_data_validation: true     # 启用数据验证
  min_data_points: 100            # 最少数据点数
  enable_sanity_checks: true      # 启用合理性检查
  
  # Quality Filters
  quality_filters:
    min_confidence_score: 0.6     # 最小置信度
    min_pattern_quality: "medium" # 最小形态质量
    enable_invalidation_filter: true # 启用失效过滤器